project:
  type: website

website:
  title: "MyQuartoDoc"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked
    contents:
      - code_block.qmd
      - css.qmd
      - cross_reference.qmd
      - figure.qmd
      - table.qmd
      - website.qmd
format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    toc: true
    link-external-icon: true
    code-block-bg: true
    code-block-border-left: false
    highlight-style: pygments




