project:
  type: website

website:
  title: "MyQuartoDoc"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked
    contents:
      - table.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



