project:
  type: website

website:
  title: "MyQuartoDoc"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked
    contents:
      - css.qmd
      - cross_reference.qmd
      - figure.qmd
      - table.qmd
format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles.css
    toc: true
    link-external-icon: true
#    link-external-newwindow: true




